[FEAT] 검색 기능 구현
thelisn/challenge-2410-eunhyeong pull request #2
Opened 2024-06-18 09:50 UTC by Witsel-Blue

검색 기능 구현 완료

2024-06-18 11:14 UTC, MANAPIE requested changes
큰 구조가 너무 자주 바뀌는 것 같아요
빠르게 픽스 바랍니다..

그리고 지난 PR에 SCSS 적용해달라고도 했고 날짜 입력도 받아야 한다고 했는데 반영이 안 되어있네요.
다음 PR에선 꼭 반영 부탁드립니다.

2024-06-18 11:14 UTC, MANAPIE commented on components/feed.vue
> +            <!--- 검색 결과 --->
주석은 작대기 2개만 써도 되는데 혹시 3개를 쓴 이유가 있을까요

2024-06-18 11:14 UTC, MANAPIE commented on components/feed.vue
> +            <div v-if="isSearched===true" class="feed_filtered">
연산자 앞뒤 띄어쓰기 (다른 곳과 스타일 맞추기)

2024-06-18 11:14 UTC, MANAPIE commented on components/header.vue
>  <style>
컴포넌트에서 정의한 css가 전역으로 적용되지 않도록 scoped 해주세요

2024-06-18 11:14 UTC, MANAPIE commented on components/post.vue
>  <style>
컴포넌트에서 정의한 css가 전역으로 적용되지 않도록 scoped 해주세요

2024-06-18 11:14 UTC, MANAPIE commented on components/search.vue
>                                  <label for="date1"></label>
라벨 텍스트 있어야 합니다.

2024-06-18 11:14 UTC, MANAPIE commented on components/search.vue
>                                  <label for="date2"></label>
라벨 텍스트 있어야 합니다.

2024-06-18 11:14 UTC, MANAPIE commented on components/search.vue
>  <style>
컴포넌트에서 정의한 css가 전역으로 적용되지 않도록 scoped 해주세요

2024-06-18 11:14 UTC, MANAPIE commented on pages/create.vue
> +                        <label for="title"></label>
라벨 텍스트 있어야 합니다.

2024-06-18 11:14 UTC, MANAPIE commented on pages/create.vue
> +            },
이건 어디에서 쓰이는 변수인가요? 심지어 내용도 mainPosts랑 똑같아요

2024-06-18 11:14 UTC, MANAPIE commented on pages/create.vue
>  <style>
컴포넌트에서 정의한 css가 전역으로 적용되지 않도록 scoped 해주세요

밑에 <style>이 또 있는데 설마 자식 컴포넌트 스타일을 부모에서 지정하려고 전역으로 한 거면 이렇게 하시면 안 되고
해당 컴포넌트에서 수정하거나... 불가피한 경우 deep 연산자를 쓰셔야 합니다.

2024-06-18 11:14 UTC, MANAPIE commented on pages/index.vue
> +    .btn-back {
전반적으로 어디는 css 정의 사이에 줄바꿈이 있고 어디는 없고 그런데 통일감 있게 해주세요

2024-06-19 16:14 UTC, MANAPIE requested changes
전반적으로 개선되어야 할 부분이 많아보입니다.
코드 구조나 코드 컨벤션은 기존에 진행했던 다른 챌린지나 최근에 진행하고 있는 홈페이지 레포를 참고하세요.


https://github.com/thelisn/challenge-2410-gyumin-vue2 (vue2)
https://github.com/thelisn/landing-fe (vue3)
https://github.com/thelisn/challenge-2410-pie (vue3/typescript)

2024-06-19 16:14 UTC, MANAPIE commented on components/feed.vue
> +            <!-- 검색 결과 --->
뒤에 것도 작대기 2개입니다..

2024-06-19 16:14 UTC, MANAPIE commented on components/feed.vue
> +                v-if="isSearched===true">
연산자 앞뒤 띄어쓰기 적용이 안 됐네요

2024-06-19 16:14 UTC, MANAPIE commented on components/post.vue
> +        & .title_wrap {
그냥 손자 선택자를 노린 거면 & 안 써도 됩니다
자기 자신에 대해서 할 경우에만 필요해요 eg) &:hover

2024-06-19 16:14 UTC, MANAPIE commented on pages/create.vue
> +                if (this.date == '') {
== 보다 === 를 써주세요 (썼을 때 문제가 없을지도 잘 확인하셔야 합니다. 자료형 주의)

2024-06-19 16:14 UTC, MANAPIE commented on pages/create.vue
> +        & .inner {
여기 파일도 & 필요 없어요

2024-06-19 16:14 UTC, MANAPIE commented on static/scss/common.scss
공통(common) 파일에 개별 페이지에 대한 CSS가 들어가면 안 됩니다.
스타일들이 각 vue 파일로 돌아가게 해주세요.

2024-06-19 16:14 UTC, MANAPIE commented on static/scss/post_detail.scss
별도로 처리되는 거 아니면 static 폴더에 넣지 않는 게 좋습니다.
assets 폴더를 만드는 것을 추천합니다.
*빌드 설정에 따라 빌드될 때 이 경로가 아닐 수도 있습니다.

2024-06-20 05:11 UTC, MANAPIE requested changes

2024-06-20 05:11 UTC, MANAPIE commented on assets/main.scss
> +@import '@/assets/scss/templates/search-form.scss';
각 컴포넌트 별로 scoped 되게 css가 적용이 되어야 하는데
이렇게 전역으로 설정하면 기존 거랑 다를 게 없네요

2024-06-20 05:11 UTC, MANAPIE commented on assets/scss/components/buttons.scss
> +    &-create {
어디는 스네이크 케이스고 어디는 케밥 케이스고 통일이 안 되어있네요

2024-06-20 05:11 UTC, MANAPIE commented on assets/scss/pages/create.scss
> +            & img {
손자를 지정할 땐 맨 앞의 &가 없어야 한다구요
다른 데도 아직 많이 남아있는데 확인 부탁드립니다

2024-06-20 09:58 UTC, Witsel-Blue commented on assets/scss/components/buttons.scss
> +    &-create {
이름이 구조상 하위일 경우 _ 스네이크 케이스, 같은 구조에서 이름만 다를 경우 - 케밥 케이스로 분리하고 있는데
모두 같은 표기명으로 바꾸는게 좋을까요..?

2024-06-20 09:59 UTC, Witsel-Blue commented on assets/main.scss
> +@import '@/assets/scss/templates/search-form.scss';
내일 다시 확인하고 고치겠습니다..!

2024-06-20 11:15 UTC, MANAPIE requested changes
말씀주신대로 내일 scss 파일 정리하는 것도 함께 보겠습니다.

2024-06-20 11:15 UTC, MANAPIE commented on assets/scss/components/buttons.scss
> +    &-create {
1. 보통은 통일되게 쓰기는 하고
2. 같은 바 계열인 스네이크와 케밥을 같이 쓰는 경우는 더 잘 없습니다
이런 특별한 규칙이 있으면 문서에 잘 적어주셔야 합니다 (리드미 등)

2024-06-20 11:15 UTC, MANAPIE commented on components/feed.vue
> +                v-if="isSearched===true">
넘어갈게요

2024-06-21 04:44 UTC, MANAPIE requested changes

2024-06-21 04:44 UTC, MANAPIE commented on pages/create.vue
> +    @import '@/assets/scss/layout/header-small.scss';
페이지마다 다를 수 있는 헤더 크기를 css를 페이지에 더 넣어서 조절하는 건 바람직하지 않습니다.
small 여부는 header에 prop으로 넘겨줘서 처리하세요.
*헤더 컴포넌트 밖에서  v-deep 같은 걸 써서 스타일을 조절하려고 하는데, 원칙적으로는 해당 컴포넌트 밖에서 스타일을 강제하는 건 좋은 구조가 아닙니다.

2024-06-21 04:44 UTC, MANAPIE commented on pages/post/_id.vue
> +    @import '@/assets/scss/layout/header-small.scss';
페이지마다 다를 수 있는 헤더 크기를 css를 페이지에 더 넣어서 조절하는 건 바람직하지 않습니다.

2024-06-21 11:39 UTC, MANAPIE commented on pages/index.vue
> +            class="main">
클래스보다는 프롭으로 제어하는 게 더 낫습니다..

2024-06-21 11:40 UTC, MANAPIE approved these changes

2024-06-21 12:17 UTC, MANAPIE commented
다음 PR에서 수정해주세요

1. 날짜를 하나만 입력했을 때 '검색어를 입력하세요'라고 뜨며 검색 안 됨 -> 다른 날짜로 입력해달라고 하든가 아님 이거만 가지고도 검색이 가능해야함 (시작일~영원히 or 영원히~종료일)
2. 검색을 하고 헤더의 뒤로가기 버튼을 누르면 검색 결과는 초기화되는데 검색 조건은 초기화가 안 돼서 이상해요

2024-06-21 12:18 UTC, merged