[FEAT] 검색조건 처리, 뒤로가기 헤더로고 클릭 기능, 상세페이지 이전 다음 버튼, SCSS 추가
thelisn/challenge-2410-eunhyeong pull request #3
Opened 2024-06-26 00:59 UTC by Witsel-Blue

- 검색 조건 처리
- 뒤로가기, 헤더로고 클릭 분기처리
- 상세 페이지 이전, 다음 버튼 추가
- SCSS 코드 리팩토링

2024-06-26 14:13 UTC, MANAPIE approved these changes
다음 PR에서는:
- 버튼, 헤더 등 컴포넌트 단의 scss도 scoped로 해서 CSS가 해당 컴포넌트에 종속되도록 하기
- 파일 명 오타 수정 typography 
- PR 날리는 사용자(파란애)랑 로컬에서 커밋하는 사용자(보라색애)가 다르게 나타나고 있는데 로컬에서 git 설정이 제대로 되어있나 확인해주세요.

2024-06-27 14:53 UTC, MANAPIE requested changes
SCSS 구조가 아직도 적절하지 않습니다.
같은 SCSS 파일이 여러 군데 import 되어있다는 것인데요,
예를 들면 button.scss는 btnback.vue와 index.vue에서 두 번 import 되는데, 아래와 같이 되어야 결과물의 코드의 중복을 최소화할 수 있습니다.
- btnback.vue, index.vue: 버튼 공통 import (심지어 지금 css에는 버튼 공통 css가 하나도 없습니다.)
- index.vue: create 버튼 css 구현
- btnback.vue: back 버튼 css 구현
사실, 이렇게 구현하려면 공통 button 컴포넌트를 따로 만들고 button에 주어진 prop에 따라 create 또는 back 버튼이 구현되도록 해야합니다.

헤더의 경우에도 제가 저번에 prop으로 구분하라고 했는데.. class로 구분을 하셨더라구요
이 부분도 같이 확인하면서 scss 구조 정리 부탁드립니다.

2024-06-28 02:42 UTC, Witsel-Blue commented
1. SCSS 폴더 구조
https://mine-it-record.tistory.com/594 참고하여 폴더 구조 생성했는데 적절하지 않은 부분을 알려주시면 감사하겠습니다!

2. 같은 SCSS 파일이 여러 군데 import 되어있다
SCSS 코드 중 공통되는 부분이 있을 경우 여러군데 import하고, 그렇지 않은 경우 scoped로 관리하는 것이라고 이해했는데 맞을까요..?

3. 공통 button 컴포넌트를 따로 만들고 button에 주어진 prop에 따라 create 또는 back 버튼이 구현되도록 해야합니다
공통되는 부분이 없어서 따로 만들었습니다!

4. 헤더의 경우에도 제가 저번에 prop으로 구분하라고 했는데.. class로 구분을 하셨더라구요
vuex에서 data로 처리하도록 했습니다! 컴포넌트에서 class 구분은 삭제했습니다.

2024-06-28 03:00 UTC, MANAPIE requested changes
회신드립니다:

1.
SCSS 폴더 구조를 말하는 게 아니고 SCSS를 사용하는 전반적인 구조를 말씀드린 겁니다.

2.
기본적으로 css는 컴포넌트에 종속되어있어 다른 컴포넌트에 영향이 없어야 하는 게 맞고,
공통 영역이 필요하면 공통 컴포넌트화를 해야합니다. 
다만 reset 같이 진짜 초월적으로 공통으로 사용되는 거는 매번 import하게 하지 않고 전역으로 적용되게끔 합니다.
(지금 중복으로 import 하고 있는 variable도 적절한 방식은 아닙니다.)

3.
넹

4.
레이아웃(헤더 포함) > 페이지
처럼 자식(페이지)에서 부모에 있는 헤더를 다룰 게 아니고
페이지(헤더 포함) 이니깐
그 페이지에 직접 포함된 자식인 헤더를 다뤄야 하는 건데

페이지에 있는 헤더에 프롭으로 프로퍼티를 직접 넘겨주면 되지 굳이 전역으로 쓸 수 있는 스테이트로 관리하는지.. 이해가 잘 안 됩니다
컴포넌트 prop 씁시다...

2024-06-30 17:27 UTC, MANAPIE approved these changes
수고하셨습니다.

2024-06-30 17:27 UTC, merged